language: none

sudo: required

dist: trusty

git:
  depth: false

addons:
  sonarcloud: true
  apt:
    sources:
     - sourceline: 'deb http://download.mono-project.com/repo/ubuntu trusty main'
       key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF'
    packages:
     - mono-complete

jdk:
  - openjdk11

before_install: 
  - wget -O os.deb http://oscript.io/downloads/1_2_0/x64/onescript-engine_1.2.0_all.deb
  - sudo dpkg -i os.deb; sudo apt install -f
  - oscript

install: 
  - sudo opm install
  - sudo opm install 1bdd
  - sudo opm install 1testrunner
  - sudo opm install coverage

script:
  - oscript ./tasks/coverage.os

after_script:
  - ./.travis-after-script.sh
